# Generated by Django 3.1.5 on 2021-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=15)),
                ('phno', models.CharField(max_length=15)),
                ('des', models.CharField(max_length=15)),
            ],
        ),
    ]
