# Generated by Django 3.2.7 on 2022-01-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abstract_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonInfo',
        ),
    ]
