# Generated by Django 3.1.5 on 2021-01-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.IntegerField()),
                ('stud_name', models.CharField(max_length=70)),
                ('stud_email', models.EmailField(max_length=70)),
                ('stud_passwd', models.CharField(max_length=150)),
            ],
        ),
    ]
